apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zora
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - pdb.yaml
  - hpa.yaml
commonLabels:
  app.kubernetes.io/name: zora
  app.kubernetes.io/part-of: zora
